export class User {
    constructor(
       public id: string,
       public create_uid: string,
       public write_uid: string,
       public create_date: string,
       public write_date: string,
       public email: string,
       public password: string,
       public first_name: string,
       public last_name: string,
       public inscube_name: string,
       public day: string,
       public month: string,
       public year: string,
       public gender: string,
       public mobile: string,
       public job: string,
       public company: string,
       public country_id: string,
       public state_id: string,
       public city_id: string,
       public image: string,
       public summary: string,
       public see_profile: string,
       public is_profile_completed: string,
       public email_verify: string,
       public email_privacy: string,
       public mobile_privacy: string,
       public post_privacy: string,
       public explainer: string,
       public active: string,
       public is_deleted: string
    ) {}
 };
 export class UserDetails {
    constructor(
       public id: string,
       public create_uid: string,
       public write_uid: string,
       public create_date: string,
       public write_date: string,
       public email: string,
       public password: string,
       public first_name: string,
       public last_name: string,
       public inscube_name: string,
       public day: string,
       public month: string,
       public year: string,
       public gender: string,
       public mobile: string,
       public job: string,
       public company: string,
       public country_id: string,
       public state_id: string,
       public city_id: string,
       public image: string,
       public summary: string,
       public see_profile: string,
       public is_profile_completed: string,
       public email_verify: string,
       public email_privacy: string,
       public mobile_privacy: string,
       public post_privacy: string,
       public explainer: string,
       public active: string,
       public is_deleted: string
    ) {}
 }